packages:
  - apps/*
  - packages/*

catalog:
  better-auth: ^1.5.4
  dotenv: ^17.3.1
  oxfmt: ^0.54.0
  typescript: ^5.9.3
  zod: ^4.3.6

allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  esbuild: true
  lefthook: true
  msw: true
  prisma: true
  sharp: true
  workerd: true

minimumReleaseAgeExclude:
  - miniflare@4.20260714.0
  - wrangler@4.112.0
