import { NextResponse } from "next/server";
import { db } from "@segmentation/db";
import { labelImage, labelProject } from "@segmentation/db/schema/app";
import { and, eq } from "drizzle-orm";

import { requireRouteUser } from "@/lib/server/route-auth";

// Returns a downloadable file for the requested format. It prefers the
// hosted result artifact (via resultKey), and falls back to a DB-derived
// export if the hosted object is unavailable.

const VALID_FORMATS = new Set(["coco", "class_pngs", "yolo"]);

export async function GET(request: Request, { params }: { params: Promise<{ id: string }> }) {
  const routeUser = await requireRouteUser(request);
  if (!routeUser) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = await params;
  const { searchParams } = new URL(request.url);
  const format = searchParams.get("format") ?? "";

  if (!VALID_FORMATS.has(format)) {
    return NextResponse.json({ error: "Invalid format" }, { status: 400 });
  }

  const [project] = await db
    .select({
      id: labelProject.id,
      name: labelProject.name,
      prompt: labelProject.prompt,
      status: labelProject.status,
      resultKey: labelProject.resultKey,
      outputCoco: labelProject.outputCoco,
      outputClassPngs: labelProject.outputClassPngs,
      outputYolo: labelProject.outputYolo,
    })
    .from(labelProject)
    .where(and(eq(labelProject.id, id), eq(labelProject.userId, routeUser.userId)))
    .limit(1);

  if (!project) {
    return NextResponse.json({ error: "Project not found" }, { status: 404 });
  }

  if (project.status !== "completed") {
    return NextResponse.json({ error: "Project is not completed" }, { status: 409 });
  }

  // Validate requested format was enabled for this project
  if (format === "coco" && !project.outputCoco) {
    return NextResponse.json({ error: "COCO output was not enabled for this project" }, { status: 400 });
  }
  if (format === "class_pngs" && !project.outputClassPngs) {
    return NextResponse.json({ error: "Per-class PNG output was not enabled for this project" }, { status: 400 });
  }
  if (format === "yolo" && !project.outputYolo) {
    return NextResponse.json({ error: "YOLO output was not enabled for this project" }, { status: 400 });
  }

  if (!project.resultKey) {
    return await buildFallbackDownload(project.id, project.name, project.prompt, format);
  }

  const baseUrl = (process.env.AWS_CLOUDFRONT_BASE_URL ?? "").replace(/\/+$/, "");
  const normalizedResultKey = project.resultKey.replace(/^\/+/, "");

  // Prefer returning a file response directly. This prevents users from seeing raw
  // CloudFront/S3 XML errors when access to the object fails.
  if (baseUrl) {
    const downloadUrl = `${baseUrl}/${normalizedResultKey}`;

    try {
      const upstream = await fetch(downloadUrl, { cache: "no-store" });
      if (upstream.ok) {
        const text = await upstream.text();
        return buildAttachmentResponse({
          fileName:
            format === "coco"
              ? "annotations.json"
              : format === "class_pngs"
                ? "class-masks-manifest.json"
                : "yolo-manifest.json",
          contentType: "application/json; charset=utf-8",
          body: text,
        });
      }
    } catch (error) {
      console.error("Failed to fetch project result from CloudFront", error);
    }
  }

  return await buildFallbackDownload(project.id, project.name, project.prompt, format);
}

async function buildFallbackDownload(
  projectId: string,
  projectName: string,
  prompt: string,
  format: string,
) {
  const images = await db
    .select({
      id: labelImage.id,
      originalName: labelImage.originalName,
      s3Key: labelImage.s3Key,
      requestId: labelImage.requestId,
      imageStatus: labelImage.imageStatus,
      errorMessage: labelImage.errorMessage,
    })
    .from(labelImage)
    .where(eq(labelImage.projectId, projectId));

  const body = JSON.stringify(
    {
      projectId,
      projectName,
      prompt,
      format,
      generatedAt: new Date().toISOString(),
      note: "Fallback export generated by dashboard because hosted result file was unavailable.",
      images,
    },
    null,
    2,
  );

  return buildAttachmentResponse({
    fileName:
      format === "coco"
        ? "annotations-fallback.json"
        : format === "class_pngs"
          ? "class-masks-fallback.json"
          : "yolo-fallback.json",
    contentType: "application/json; charset=utf-8",
    body,
  });
}

function buildAttachmentResponse({
  fileName,
  contentType,
  body,
}: {
  fileName: string;
  contentType: string;
  body: string;
}) {
  return new NextResponse(body, {
    status: 200,
    headers: {
      "Cache-Control": "no-store",
      "Content-Disposition": `attachment; filename="${fileName}"`,
      "Content-Type": contentType,
    },
  });
}
